### PR TITLE
Pull Rq for file handling APIs

### PR DESCRIPTION
**Pull request by teande**
Added File Policy
Added File Rules
Modified Makefile with install and test blocks
Modified gitignore to add vendor/ dir
Added logger for debugging requests

### CODE REVIEW

**Comment by jabielecki** [comment]
On 7.2.5 it fails tests, and for now 7.2.5 is the version we focus on:
```
2024/07/29 16:38:02 [DEBUG] HTTP Request: POST, https://10.50.202.38/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/filepolicies, {"name":"file_policy_1","description":"My file policy","archiveDepth":"3","archiveDepthAction":true,"blockEncryptedArchives":false,"cleanList":true,"customDetectionList":true,"firstTimeFileAnalysis":true,"inspectArchives":false,"threatScore":"High"}
2024/07/29 16:38:03 [DEBUG] HTTP Response: {"error":{"category":"FRAMEWORK","messages":[{"description":"Read only resource."}],"severity":"ERROR"}}
```

If you see any way to make it work on 7.2.5, please update the PR. Otherwise let's put the GH issue (the ticket) on hold, and close this PR. It can be re-opened at any time.

**Comment by teande** [comment]
The issue here is that file policy API for POST PUT DELETE are only supported 7.4.1 onwards. 
That's why it fails.

Fix:
Uncomment below line.

gen/definitions/file_policy.yaml:
# minimum_version: 7.4.0

**Comment by jabielecki** [comment]
> # minimum_version: 7.4.0

Again, I'd rather recommend to put the GH issue (the ticket) on hold, and close this PR. It can be re-opened at any time.

Reason: we don't want "dead" code in main. We presently don't have CI on 7.4.1 nor 7.4.0, so is the code gets accidentally broken, there is nothing that would detect it.

**Comment by teande** [comment]
Hello Jakub,
Good morning.

Yes, we can put it on hold right now. Just ping me once on Webex when the 7.4 is added in the pipeline and I’ll reopen the PR again.

Thank you.

From: Jakub Bielecki ***@***.***>
Date: Friday, 2 August 2024 at 1:17 AM
To: netascode/terraform-provider-fmc ***@***.***>
Cc: Charan Teja (teande) ***@***.***>, Author ***@***.***>
Subject: Re: [netascode/terraform-provider-fmc] Pull Rq for file handling APIs (PR #110)

minimum_version: 7.4.0

Again, I'd rather recommend to put the GH issue (the ticket) on hold, and close this PR. It can be re-opened at any time.

Reason: we don't want "dead" code in main. We presently don't have CI on 7.4.1 nor 7.4.0, so is the code gets accidentally broken, there is nothing that would detect it.

**Comment by rchrabas** [comment]
File Policy planed in #196

**Pull request closed without merging**
